public let words = [
  "dance", "skip", "jump",
  "shark", "chicken", "alligator",
  "chair", "robot", "head",
  "smile", "baseball", "bird",
  "happy", "scissors", "cheek",
  "back", "jump", "drink",
  "ice", "car", "airplane",
  "clap", "circle", "pillow",
  "pinch", "kick", "dog",
  "basketball", "sleep", "camera",
  "kangaroo", "arm", "eat",
  "prayer", "elephant", "blink",
  "doll", "spider", "point",
  "balloon", "book", "glasses",
  "stop", "sneeze", "mouth",
  "draw", "football", "telephone",
  "pig", "wave", "door",
  "tail", "turtle", "baby",
  "ear", "monkey", "hopscotch",
  "mosquito", "toothbrush", "ring"
]
